apiVersion: v1
kind: PersistentVolume
metadata:
  name: rancher-pv
  namespace: rancher
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/home/brsoni/kube/rancher/data"
