apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rancher-pvc
  namespace: rancher
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeName: rancher-pv
