apiVersion: v1
kind: PersistentVolume # Create a PV
metadata:
  name: postgresql-data # Sets PV's name
  labels:
    type: local # Sets PV's type to local
spec:
  storageClassName: manual
  capacity:
    storage: 256Mi # Sets PV Volume
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/brsoni/kube/postgresql/volume" # Sets the volume's path
