apiVersion: v1
kind: Service
metadata:
  name: adguard-service
  namespace: adguard
spec:
  selector:
    app: adguard
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
    name: http
  - protocol: UDP
    port: 53
    targetPort: 53
    name: dns
  type: NodePort
