apiVersion: v1
kind: PersistentVolume
metadata:
  name: adguard-pv
  namespace: adguard
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/home/brsoni/kube/adguard/data"
    path: "/home/brsoni/kube/adguard/conf"
